import numpy as np

y = np.array([1, 2, 3, 4, 5])
k = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
v = np.hstack([y * y, y, np.ones_like(y)])
u = np.zeros(5).reshape(-1, 1)
w = np.zeros((5, 1))
z = np.vander(y, 3)
x = np.vstack([y * y, y, np.ones_like(y)])
c = np.array([0,2,2,2,2,2,0,2,2,2,2,2,0,0,2,0,1,2,0,0,1,1,1,2,0,1,0,1,1,1,0,0,1,1,1,1,])
a = np.unique(c)
b = (c == 0)
d = (c == 0).astype(int)

print('y', y)
print(y.shape)
print('k', k)
print(k.shape)
print(k.reshape(-1, 1))
print('v', v)
print('u', u)
print('w', w)
print('z', z)
print('x', x)
print(y.T)
print("y.T @ y", y.T @ y)
print(y @ y)
print(y @ y.T)
print(y.T.shape)
print(y.reshape(-1, 1).shape)
print('a', a)
print('b', b)
print('d', d)